#!/usr/bin/env bash
# Define environment variables to customize the command line interface

# Ensure that all bin and sbin folders are in PATH, if they are not symlinks
colon_path=":$PATH:"
for path_dir in /usr/local/bin /bin /usr/bin; do
  if [ ! -L "$path_dir" ] && [ -d "$path_dir" ] && [ "${colon_path%:$path_dir:*}" = "$colon_path" ]; then
    PATH="$path_dir:$PATH"
  fi
done
for path_dir in /usr/local/sbin /sbin /usr/sbin; do
  if [ "$(id -u)" -eq 0 ] && [ ! -L "$path_dir" ] && [ -d "$path_dir" ] && [ "${colon_path%:$path_dir:*}" = "$colon_path" ]; then
    PATH="$path_dir:$PATH"
  fi
done
export PATH
unset path_dir

# Find real home directory
# Try sudo user
if [ -z "$REAL_HOME" ] && [ -n "$SUDO_USER" ]; then
  REAL_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
fi

# Use current $HOME variable
if [ -z "$REAL_HOME" ]; then
  REAL_HOME="$HOME"
fi
export REAL_HOME

# Add home in path
homebin="$REAL_HOME/bin"
if [ -d "$homebin" ] && [ "${colon_path%:$homebin:*}" = "$colon_path" ]; then
  export PATH="$homebin:$PATH"
fi
unset homebin

homelocalbin="$REAL_HOME/.local/bin"
if [ -d "$homelocalbin" ] && [ "${colon_path%:$homelocalbin:*}" = "$colon_path" ]; then
  export PATH="$homelocalbin:$PATH"
fi
unset homelocalbin

homelocalsbin="$REAL_HOME/.local/sbin"
if [ "$(id -u)" -eq 0 ] && [ -d "$homelocalsbin" ] && [ "${colon_path%:$homelocalsbin:*}" = "$colon_path" ]; then
  export PATH="$homelocalsbin:$PATH"
fi
unset homelocalsbin

unset colon_path

# Python configuration
if [ -r "$REAL_HOME/.pythonrc" ]; then
  export PYTHONSTARTUP="$REAL_HOME/.pythonrc"
fi

# Prevent Erase in Line (EL) to Right (\33[K) in the colored output of grep.
# Please read grep man page for further information.
export GREP_COLORS='ne'

# Use Vim
if [ -x /usr/bin/vim ] || command -v vim >/dev/null; then
  export EDITOR=vim
fi

# Use less
if [ -x /usr/bin/less ] || command -v less >/dev/null; then
  # Force -R = --RAW-CONTROL-CHARS to have colors in less
  export LESS='--RAW-CONTROL-CHARS'
  export LESSCOLOR='yes'
  export PAGER='less --RAW-CONTROL-CHARS'
  # Do not use .lesshst
  export LESSHISTFILE='/dev/null'
fi

# Make less more friendly for non-text input files, see lesspipe(1)
if [ -x /usr/bin/lesspipe ]; then
  export LESSOPEN="| /usr/bin/lesspipe %s"
  export LESSCLOSE="/usr/bin/lesspipe %s %s"
fi

# Use most to display man pages using colors
if [ -x /usr/bin/most ] || command -v most >/dev/null; then
  export MANPAGER=most
fi

# Enable GCC colors (since GCC 4.8.0)
export GCC_COLORS=1

# Use nice ls colors
eval "$(dircolors --bourne-shell)"

# Warn about dangerous environment
if [ -s /etc/ld.so.preload ]; then
  (tput bold && tput setaf 1) 2>/dev/null
  echo >&2 'Warning: /etc/ld.so.preload is present on this system!'
  tput sgr0 2>/dev/null
fi

if [ -n "${LD_PRELOAD}" ]; then
  (tput bold && tput setaf 1) 2>/dev/null
  echo >&2 'Warning: LD_PRELOAD is set!'
  tput sgr0 2>/dev/null
fi

if [ -n "${LD_LIBRARY_PATH}" ]; then
  (tput bold && tput setaf 1) 2>/dev/null
  echo >&2 'Warning: LD_LIBRARY_PATH is set!'
  tput sgr0 2>/dev/null
fi

export JAVA_TOOL_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'
