icons_format = "{icon}"

[theme]
theme = "my_theme.toml"

[icons]
icons = "my_icons.toml"

[[block]]
block = "net"
format = "$icon  $device {$ssid $signal_strength |}$ip ^icon_net_down$speed_down.eng(unit:b,prefix:K,hide_unit:true,width:4)bps $graph_down ^icon_net_up$speed_up.eng(unit:b,prefix:K,hide_unit:true,width:4)bps $graph_up"

[[block]]
block = "disk_space"
path = "/"
warning = 5
alert = 1
alert_unit = "GB"
format = "$icon $path $available"

[[block]]
block = "disk_space"
path = "/home"
warning = 5
alert = 1
alert_unit = "GB"
format = "$icon $path $available"

[[block]]
block = "cpu"
format = "$barchart$utilization"

[[block]]
block = "load"
format = "$icon  $1m.eng(width:3) $5m.eng(width:3) $15m.eng(width:3)"

[[block]]
block = "memory"
format = "$icon $mem_avail_percents"

[[block]]
block = "battery"
good = 85
format = "$icon $time $percentage"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"French (alt.)" = "FR"
"English (US, intl., with dead keys)" = "US"

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S W%V')"
