# zoxide-query
# Autogenerated from man page /usr/share/man/man1/zoxide-query.1
complete -c zoxide-query -l all -d 'Show deleted directories'
complete -c zoxide-query -l exclude -d 'Exclude a path from query results'
complete -c zoxide-query -s h -l help -d 'Print help information'
complete -c zoxide-query -s i -l interactive -d 'Use interactive selection.  This option requires fzf(1)'
complete -c zoxide-query -s l -l list -d 'List all results, rather than just the one with the highest frecency'
complete -c zoxide-query -s s -l score -d 'Print the calculated score as well as the matched path'

