# zoxide-import
# Autogenerated from man page /usr/share/man/man1/zoxide-import.1
complete -c zoxide-import -l from -d 'The format of the database being imported: . TS tab(|); l l'
complete -c zoxide-import -s h -l help -d 'Print help information'
complete -c zoxide-import -l merge -d 'By default, the import fails if the current database is not already empty'

