live_config_reload = true
working_directory = "None"

[bell]
animation = "Ease"
color = "#00356b"
command = "None"
duration = 150

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#505354"
blue = "#63AAFF"
cyan = "#00FFFF"
green = "#55FF55"
magenta = "#CD00CD"
red = "#FF2222"
white = "#F9F9F9"
yellow = "#FEED6C"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#286dc0"
cyan = "#009999"
green = "#82b414"
magenta = "#8c54fe"
red = "#bb0000"
white = "#ccccc6"
yellow = "#fd971f"

[colors.primary]
background = "#000000"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#F9F9F9"

[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
style = "Block"
thickness = 0.2
unfocused_hollow = true
vi_mode_style = "None"

[font]
size = 11.0

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Oblique"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "DejaVu Sans Mono"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono"
style = "Book"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 10

[selection]
save_to_clipboard = true

[shell]
program = "/bin/bash"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
